name: study_mate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.0
  # dwds: ^19.0.0
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.4
  firebase_auth: ^4.4.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/